### ISSUE TITLE
不能执行任务？？

### ISSUE THREAD

**Issue by authorz** [ArrowJustDoIt/crontab#3]
运行环境：
```
Linux   version | CentOS Linux 7.6
PHP     version | PHP/7.3.10
Mysql   version | 5.5
Laravel version | 6.3.022:26:13 UTC 2017 x86_64
Server          | nginx/1.14.0
Cache driver    | file
Session driver  | file
```
已经再`admin.php`中添加：
```
'extensions' => [
        'crontab' => [
            'enable' => true,
        ]
    ]
```
添加完任务后不执行，已开启`shell_exec()`
添加完以后列表里`下次预计时间`为空，日志里面也没有
请问我还有什么没有操作吗？？

**Comment by ArrowJustDoIt** [comment]
你好,有在服务器设置crontab吗?

crontab -e #回车
#>>后面为日志文件,可加可不加
* * * * * php /your web dir/artisan autotask:run >>/home/crontab.log 2>&1

**Comment by ArrowJustDoIt** [comment]
`crontab -e #回车
#>>后面为日志文件,可加可不加
* * * * * php /your web dir/artisan autotask:run >>/home/crontab.log 2>&1`

**Comment by ArrowJustDoIt** [comment]
你好,有在服务器设置crontab吗?
```
crontab -e #回车
#>>后面为日志文件,可加可不加
 * * * * * php /your web dir/artisan autotask:run >>/home/crontab.log 2>&1
```

**Comment by sunxiyuan** [comment]
遇到了相同的问题。主要是没有错误日志可以看，也不知道是哪里出错了。我手工执行了`php artisan autotask:run`也不会触发定时任务。shell_exec()确认是开启状态

**Comment by sunxiyuan** [comment]
知道原因了。是cron表达式写错了

**Comment by ArrowJustDoIt** [comment]
@sunxiyuan 好的
