### ISSUE TITLE
怎么用不了？

### ISSUE THREAD

**Issue by huaxiuyiwei** [ArrowJustDoIt/crontab#6]
在/admin/crontabs页面中创建一个任务，用crontab -l命令查看，显示no crontab for ubuntu，crontab -e命令也显示no crontab for ubuntu - using an empty one，不知道该怎么用？

**Comment by ArrowJustDoIt** [comment]
@huaxiuyiwei 切换到root用户,如果是vim 输入 `export EDITOR=vim` 如果是emacs或者nano 就改成对应的编辑器,或者输入`select-editor` 选 3

**Comment by huaxiuyiwei** [comment]
可能是我理解错误了，命令可能不是crontab -e，而是crontab -e # 然后回车就弹出一个文本输入界面了，然后 * * * * * php /your web dir/artisan autotask:run    然后保存 。  我去掉了 >>/home/crontab.log 2>&1 。因为带上这部分就没效果，我试了一下直接运行这个命令php /your web dir/artisan autotask:run >>/home/crontab.log 2>&1  显示没有权限写入log。然后就可以使用了，谢谢大佬分享和答复
