### ISSUE TITLE
定时get请求url时报错

### ISSUE THREAD

**Issue by yimijianfang** [ArrowJustDoIt/crontab#7]
接口确实比较耗时，平时在40s左右。用postman调用接口能正常返回，定时执行报错：
`http://localhost:9998/api/schedule/getMonitor 请求成功失败: Client error: GET http://localhost:9998/api/schedule/getMonitor resulted in a `404 Not Found` response: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" co (truncated...)  `

**Comment by ArrowJustDoIt** [comment]
路由有确认过是否正确吗?

**Comment by yimijianfang** [comment]
> 路由有确认过是否正确吗?

路由没问题，postman是可以的。我也觉得奇怪超时不应该是500+的报错嘛，怎么会是404~
现在设置了set_time_limit(0);目前一切正常

**Comment by ArrowJustDoIt** [comment]
恩恩,好的

**Comment by yimijianfang** [comment]
> 补充，nginx新增了以下配置解决了超时问题
```
fastcgi_connect_timeout 600; fastcgi连接超时时间，默认60秒
fastcgi_send_timeout nginx  600; 进程向 fastcgi 进程发送请求过程的超时时间，默认值60秒
fastcgi_read_timeout fastcgi 600; 进程向 nginx 进程发送输出过程的超时时间，默认值60秒
```
