### ISSUE TITLE
兼容dcat-admin

### ISSUE THREAD

**Issue by NightDragonOne** [ArrowJustDoIt/crontab#8]
作者有没有意向把这个插件兼容dcat-admin？
这个插件挺好用的，但项目已经往dcat-admin上迁移，从目前上看，dcat要好一些，您要是忙或者没有意向的话，我打算迁移这个插件到dcat

**Comment by ArrowJustDoIt** [comment]
感谢,已有兼容计划

**Comment by ArrowJustDoIt** [comment]
https://github.com/ArrowJustDoIt/dcat-admin-crontab-extension
已经兼容,enjoy it :)
